language: node_js
node_js:
- node
- '8'
services:
- mysql
before_install:
- mysql -u root --password="" < test/travis.sql
deploy:
  provider: heroku
  api_key:
    secure: n/GqL2OvPqD5LsKJjwTPcJeX3KVyPSUJU9BSxLHLvpB/Y7CYCNoNIRPF3kTyXTXlqTZ38l3Dni9VxxXIN1mu4Bps0Z5Oz7jyAS3YY8NOhruBIzai7LDU03XsNysZC6vPaTm9c0tJeSQOACWWWUOOJPdL8jiWc/sqZ4nPPHaNh57k6Ev1MnYATxoqUwX3Jz/OBxSSTontuJug0Paj2/6iQWhKNFbSTXg34qimLKftv+gLdUORITlrVVx1w9xiwfvaLSTWc473yPWfPnLBxXwRiRS6N6f+d+cKyxvZ2r9L5bYuXP0pLutrQl4Nan8rAFn1epDn8+fQi0VmAO1uAxWxJxkSAoURswbPABWKaFKt0ohv9CDG1NOoMhOlHE7ahm5x8iQ020FrepdPZ6FlTdNsKhPuNuTB01+FgeVJeBDojU4oyFbakTsSEi5WEQGLWOQ9VlS7Ipi/oRrUaUO3IiHetc4k3cdmpSbwpzQqtil4RkIW9pH20OksjiSWtDEu+d/dLy2kiniWg9kj5wzqyA7L3EtHHjkeAQyqj83Q/p42+8Yosr2XGPMMlICotfOhJUqMPcUhe+52FEifD3aAB0mpcX7hYzK2i89zdh9j3QBHTYHYL1xb6jgNXK/2p9/ZL84pnYD2CVqj+HY1Zil8L9j00HRJ/R6gbU84xDeAHNr6Jgw=
  app: nodejstdd
  on:
    repo: jalilbengoufa/nodejsTDD
